apiVersion: apps/v1
kind: Deployment
metadata:
  name: shuttleverse-aggregator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shuttleverse-aggregator
  template:
    metadata:
      labels:
        app: shuttleverse-aggregator
    spec:
      containers:
        - name: aggregator
          image: docker-user/shuttleverse-aggregator:latest
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: MONGODB_PROD_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_PROD_URI